### ISSUE TITLE
flash dont work anymore

### ISSUE THREAD

**Issue by megathelegend2** [NeonK/swfgalaxy#21]
`If` you were to change the link from "js/swfcoin.js" to "https://e9x.github.io/ruffle/ruffle.js" a lot of your games would start working again.

<script src="js/swfcoin.js"></script> VS `<script src="https://e9x.github.io/ruffle/ruffle.js"></script>
`

**Comment by billyb2** [comment]
Would you wanna make a pull request ;) if so, I'd be happy to merge it.

**Comment by megathelegend2** [comment]
ya sure. im new to github so i will have to figure it out. also only a few of the games would still work because ruffle does not support action script 3(at least i think that is what it is.) some games just never load.

**Comment by billyb2** [comment]
Closing due to yuor PR, thank you!
